// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOcthtpJ-L1XoUlrxCCLOEc7Z48EFSEIE',
    appId: '1:592459094415:web:dfecc9722bee8d90ed13fa',
    messagingSenderId: '592459094415',
    projectId: 'nti-1-9b971',
    authDomain: 'nti-1-9b971.firebaseapp.com',
    storageBucket: 'nti-1-9b971.firebasestorage.app',
    measurementId: 'G-XFPLEVHX9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcLoB9tEPizop5qfwnbm_qFaSNVXE5leE',
    appId: '1:592459094415:android:1f2f7497f4a7c3d0ed13fa',
    messagingSenderId: '592459094415',
    projectId: 'nti-1-9b971',
    storageBucket: 'nti-1-9b971.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjEWdEvUGcWBfViN6nY3K5-cYSPBYJLCw',
    appId: '1:592459094415:ios:70d95aef9b801a59ed13fa',
    messagingSenderId: '592459094415',
    projectId: 'nti-1-9b971',
    storageBucket: 'nti-1-9b971.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjEWdEvUGcWBfViN6nY3K5-cYSPBYJLCw',
    appId: '1:592459094415:ios:70d95aef9b801a59ed13fa',
    messagingSenderId: '592459094415',
    projectId: 'nti-1-9b971',
    storageBucket: 'nti-1-9b971.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOcthtpJ-L1XoUlrxCCLOEc7Z48EFSEIE',
    appId: '1:592459094415:web:c25778665f416120ed13fa',
    messagingSenderId: '592459094415',
    projectId: 'nti-1-9b971',
    authDomain: 'nti-1-9b971.firebaseapp.com',
    storageBucket: 'nti-1-9b971.firebasestorage.app',
    measurementId: 'G-99HQGL7DRZ',
  );

}